// Reference content for the F1 cheat sheet: every supported worksheet
// function (with syntax + a worked example) and every keyboard shortcut.
// Kept separate from the engine so the help text can grow without touching
// evaluation code — every name listed here must exist in FUNCTIONS.

export const FUNCTION_CATEGORIES = ["Math", "Statistical", "Logical", "Information", "Lookup", "Text", "Date & Time", "Financial", "Aggregation"];

const fn = (category, name, syntax, description, example) => ({ category, name, syntax, description, example });

export const FUNCTION_CATALOG = [
    // Math
    fn("Math", "SUM", "SUM(number1, [number2], …)", "Adds numbers and ranges.", "=SUM(A2:A10)"),
    fn("Math", "PRODUCT", "PRODUCT(number1, …)", "Multiplies all the numbers given.", "=PRODUCT(A2:A4)"),
    fn("Math", "SUMPRODUCT", "SUMPRODUCT(array1, [array2], …)", "Multiplies corresponding items and sums the products.", "=SUMPRODUCT(B2:B5, C2:C5)"),
    fn("Math", "SUMIF", "SUMIF(range, criteria, [sum_range])", "Sums cells that meet one condition.", '=SUMIF(A:A, "Delhi", C:C)'),
    fn("Math", "SUMIFS", "SUMIFS(sum_range, range1, criteria1, …)", "Sums cells that meet every condition.", '=SUMIFS(C:C, A:A, "Delhi", B:B, ">50000")'),
    fn("Math", "ABS", "ABS(number)", "Absolute value.", "=ABS(-4)"),
    fn("Math", "MOD", "MOD(number, divisor)", "Remainder after division (sign follows the divisor).", "=MOD(10, 3)"),
    fn("Math", "QUOTIENT", "QUOTIENT(numerator, denominator)", "Integer part of a division.", "=QUOTIENT(10, 3)"),
    fn("Math", "POWER", "POWER(number, power)", "Raises a number to a power (same as ^).", "=POWER(2, 10)"),
    fn("Math", "SQRT", "SQRT(number)", "Square root.", "=SQRT(144)"),
    fn("Math", "INT", "INT(number)", "Rounds down to the nearest integer.", "=INT(-3.7)"),
    fn("Math", "TRUNC", "TRUNC(number, [digits])", "Cuts off decimals without rounding.", "=TRUNC(3.789, 1)"),
    fn("Math", "SIGN", "SIGN(number)", "1, 0 or -1 for the number's sign.", "=SIGN(-12)"),
    fn("Math", "PI", "PI()", "The constant π.", "=PI()*A2^2"),
    fn("Math", "EXP", "EXP(number)", "e raised to a power.", "=EXP(1)"),
    fn("Math", "LN", "LN(number)", "Natural logarithm.", "=LN(10)"),
    fn("Math", "LOG", "LOG(number, [base])", "Logarithm to a base (10 by default).", "=LOG(8, 2)"),
    fn("Math", "LOG10", "LOG10(number)", "Base-10 logarithm.", "=LOG10(1000)"),
    fn("Math", "ROUND", "ROUND(number, digits)", "Rounds half away from zero.", "=ROUND(2.345, 2)"),
    fn("Math", "ROUNDUP", "ROUNDUP(number, digits)", "Rounds away from zero.", "=ROUNDUP(3.141, 2)"),
    fn("Math", "ROUNDDOWN", "ROUNDDOWN(number, digits)", "Rounds toward zero.", "=ROUNDDOWN(3.149, 2)"),
    fn("Math", "MROUND", "MROUND(number, multiple)", "Rounds to the nearest multiple.", "=MROUND(17, 5)"),
    fn("Math", "CEILING", "CEILING(number, significance)", "Rounds up to a multiple.", "=CEILING(4.3, 0.5)"),
    fn("Math", "FLOOR", "FLOOR(number, significance)", "Rounds down to a multiple.", "=FLOOR(4.7, 0.5)"),
    fn("Math", "EVEN", "EVEN(number)", "Rounds up to the next even integer.", "=EVEN(3)"),
    fn("Math", "ODD", "ODD(number)", "Rounds up to the next odd integer.", "=ODD(2)"),
    fn("Math", "RAND", "RAND()", "Random number between 0 and 1 (F9 re-rolls).", "=RAND()"),
    fn("Math", "RANDBETWEEN", "RANDBETWEEN(bottom, top)", "Random whole number in a range.", "=RANDBETWEEN(1, 100)"),
    fn("Math", "FACT", "FACT(number)", "Factorial.", "=FACT(5)"),
    fn("Math", "COMBIN", "COMBIN(n, k)", "Number of combinations.", "=COMBIN(10, 3)"),
    fn("Math", "PERMUT", "PERMUT(n, k)", "Number of permutations.", "=PERMUT(10, 3)"),
    fn("Math", "GCD", "GCD(number1, …)", "Greatest common divisor.", "=GCD(24, 36)"),
    fn("Math", "LCM", "LCM(number1, …)", "Least common multiple.", "=LCM(4, 6)"),

    // Statistical
    fn("Statistical", "COUNT", "COUNT(value1, …)", "Counts cells containing numbers.", "=COUNT(A2:A100)"),
    fn("Statistical", "COUNTA", "COUNTA(value1, …)", "Counts non-empty cells.", "=COUNTA(A2:A100)"),
    fn("Statistical", "COUNTBLANK", "COUNTBLANK(range)", "Counts empty cells.", "=COUNTBLANK(A2:A100)"),
    fn("Statistical", "COUNTIF", "COUNTIF(range, criteria)", "Counts cells meeting a condition (wildcards * ? ~).", '=COUNTIF(A1:A100, "Delhi*")'),
    fn("Statistical", "COUNTIFS", "COUNTIFS(range1, criteria1, …)", "Counts rows meeting every condition.", '=COUNTIFS(A:A, "Delhi", B:B, ">50")'),
    fn("Statistical", "AVERAGE", "AVERAGE(number1, …)", "Arithmetic mean.", "=AVERAGE(B2:B20)"),
    fn("Statistical", "AVERAGEIF", "AVERAGEIF(range, criteria, [average_range])", "Average of cells meeting a condition.", '=AVERAGEIF(A:A, "Delhi", C:C)'),
    fn("Statistical", "AVERAGEIFS", "AVERAGEIFS(average_range, range1, criteria1, …)", "Average of cells meeting every condition.", '=AVERAGEIFS(C:C, A:A, "Delhi", B:B, ">0")'),
    fn("Statistical", "MEDIAN", "MEDIAN(number1, …)", "Middle value.", "=MEDIAN(B2:B20)"),
    fn("Statistical", "MODE.SNGL", "MODE.SNGL(number1, …)", "Most frequent value.", "=MODE.SNGL(B2:B20)"),
    fn("Statistical", "MIN", "MIN(number1, …)", "Smallest value.", "=MIN(B2:B20)"),
    fn("Statistical", "MAX", "MAX(number1, …)", "Largest value.", "=MAX(B2:B20)"),
    fn("Statistical", "MINIFS", "MINIFS(min_range, range1, criteria1, …)", "Smallest value meeting conditions.", '=MINIFS(C:C, A:A, "Delhi")'),
    fn("Statistical", "MAXIFS", "MAXIFS(max_range, range1, criteria1, …)", "Largest value meeting conditions.", '=MAXIFS(C:C, A:A, "Delhi")'),
    fn("Statistical", "LARGE", "LARGE(array, k)", "k-th largest value.", "=LARGE(B2:B20, 2)"),
    fn("Statistical", "SMALL", "SMALL(array, k)", "k-th smallest value.", "=SMALL(B2:B20, 2)"),
    fn("Statistical", "RANK.EQ", "RANK.EQ(number, ref, [order])", "Rank of a number in a list (0 = descending).", "=RANK.EQ(B2, $B$2:$B$20)"),
    fn("Statistical", "PERCENTILE.INC", "PERCENTILE.INC(array, k)", "k-th percentile (0–1, inclusive).", "=PERCENTILE.INC(B2:B20, 0.9)"),
    fn("Statistical", "QUARTILE.INC", "QUARTILE.INC(array, quart)", "Quartile 0–4.", "=QUARTILE.INC(B2:B20, 1)"),
    fn("Statistical", "STDEV.S", "STDEV.S(number1, …)", "Sample standard deviation.", "=STDEV.S(B2:B20)"),
    fn("Statistical", "STDEV.P", "STDEV.P(number1, …)", "Population standard deviation.", "=STDEV.P(B2:B20)"),
    fn("Statistical", "VAR.S", "VAR.S(number1, …)", "Sample variance.", "=VAR.S(B2:B20)"),
    fn("Statistical", "VAR.P", "VAR.P(number1, …)", "Population variance.", "=VAR.P(B2:B20)"),
    fn("Statistical", "CORREL", "CORREL(array1, array2)", "Correlation coefficient.", "=CORREL(B2:B20, C2:C20)"),
    fn("Statistical", "COVARIANCE.P", "COVARIANCE.P(array1, array2)", "Population covariance.", "=COVARIANCE.P(B2:B20, C2:C20)"),
    fn("Statistical", "COVARIANCE.S", "COVARIANCE.S(array1, array2)", "Sample covariance.", "=COVARIANCE.S(B2:B20, C2:C20)"),

    // Logical
    fn("Logical", "IF", "IF(test, value_if_true, [value_if_false])", "Returns one value or another depending on a test.", '=IF(B2>=50, "Pass", "Fail")'),
    fn("Logical", "IFS", "IFS(test1, value1, [test2, value2], …)", "First value whose test is TRUE.", '=IFS(B2>=90,"A",B2>=75,"B",TRUE,"C")'),
    fn("Logical", "SWITCH", "SWITCH(expr, value1, result1, …, [default])", "Matches an expression against a list of values.", '=SWITCH(A2, 1, "Low", 2, "Mid", "High")'),
    fn("Logical", "AND", "AND(logical1, …)", "TRUE if every argument is TRUE.", "=AND(B2>0, C2>0)"),
    fn("Logical", "OR", "OR(logical1, …)", "TRUE if any argument is TRUE.", "=OR(B2>100, C2>100)"),
    fn("Logical", "NOT", "NOT(logical)", "Reverses TRUE/FALSE.", "=NOT(ISBLANK(A2))"),
    fn("Logical", "XOR", "XOR(logical1, …)", "TRUE if an odd number of arguments are TRUE.", "=XOR(A2, B2)"),
    fn("Logical", "IFERROR", "IFERROR(value, value_if_error)", "Replaces any error with a fallback.", "=IFERROR(A2/B2, 0)"),
    fn("Logical", "IFNA", "IFNA(value, value_if_na)", "Replaces #N/A with a fallback.", '=IFNA(VLOOKUP(A2, E:F, 2, FALSE), "Missing")'),
    fn("Logical", "TRUE", "TRUE()", "The logical value TRUE.", "=TRUE()"),
    fn("Logical", "FALSE", "FALSE()", "The logical value FALSE.", "=FALSE()"),
    fn("Logical", "CHOOSE", "CHOOSE(index, value1, value2, …)", "Picks a value by position.", '=CHOOSE(2, "Red", "Green", "Blue")'),

    // Information
    fn("Information", "ISBLANK", "ISBLANK(value)", "TRUE if the cell is empty.", "=ISBLANK(A2)"),
    fn("Information", "ISNUMBER", "ISNUMBER(value)", "TRUE for numbers.", "=ISNUMBER(A2)"),
    fn("Information", "ISTEXT", "ISTEXT(value)", "TRUE for text.", "=ISTEXT(A2)"),
    fn("Information", "ISLOGICAL", "ISLOGICAL(value)", "TRUE for TRUE/FALSE values.", "=ISLOGICAL(A2)"),
    fn("Information", "ISERROR", "ISERROR(value)", "TRUE for any error.", "=ISERROR(A2/B2)"),
    fn("Information", "ISERR", "ISERR(value)", "TRUE for any error except #N/A.", "=ISERR(A2)"),
    fn("Information", "ISNA", "ISNA(value)", "TRUE only for #N/A.", "=ISNA(MATCH(A2, E:E, 0))"),
    fn("Information", "ISEVEN", "ISEVEN(number)", "TRUE for even numbers.", "=ISEVEN(A2)"),
    fn("Information", "ISODD", "ISODD(number)", "TRUE for odd numbers.", "=ISODD(A2)"),
    fn("Information", "TYPE", "TYPE(value)", "1 number, 2 text, 4 logical, 16 error, 64 array.", "=TYPE(A2)"),
    fn("Information", "CELL", "CELL(info_type, [reference])", 'Info about a cell: "address", "row", "col", "contents", "type".', '=CELL("address", B3)'),
    fn("Information", "ROW", "ROW([reference])", "Row number of a reference (or this cell).", "=ROW()"),
    fn("Information", "COLUMN", "COLUMN([reference])", "Column number of a reference.", "=COLUMN(C1)"),
    fn("Information", "ROWS", "ROWS(array)", "Number of rows in a range.", "=ROWS(A2:A50)"),
    fn("Information", "COLUMNS", "COLUMNS(array)", "Number of columns in a range.", "=COLUMNS(A1:F1)"),
    fn("Information", "NA", "NA()", "Returns the #N/A error.", "=NA()"),

    // Lookup & arrays
    fn("Lookup", "XLOOKUP", "XLOOKUP(lookup, lookup_array, return_array, [if_not_found], [match_mode], [search_mode])", "Modern lookup in any direction; match_mode 0 exact, -1/1 next smaller/larger, 2 wildcard.", '=XLOOKUP(A2, E:E, F:F, "Not Found")'),
    fn("Lookup", "VLOOKUP", "VLOOKUP(lookup, table, col_index, [approximate])", "Looks down the first column; FALSE for exact match.", "=VLOOKUP(A2, E:G, 3, FALSE)"),
    fn("Lookup", "HLOOKUP", "HLOOKUP(lookup, table, row_index, [approximate])", "Looks across the first row.", "=HLOOKUP(\"Q2\", A1:E4, 3, FALSE)"),
    fn("Lookup", "INDEX", "INDEX(array, row, [column])", "Value at a row/column position (0 = whole row/column).", "=INDEX(F:F, MATCH(A2, E:E, 0))"),
    fn("Lookup", "MATCH", "MATCH(lookup, array, [type])", "Position of a value (0 exact, 1 ≤ sorted asc, -1 ≥ sorted desc).", "=MATCH(A2, E:E, 0)"),
    fn("Lookup", "XMATCH", "XMATCH(lookup, array, [match_mode], [search_mode])", "Position of a value with XLOOKUP's match modes.", "=XMATCH(A2, E2:E100)"),
    fn("Lookup", "FILTER", "FILTER(array, include, [if_empty])", "Rows (or columns) where include is TRUE. Spills.", "=FILTER(A1:C10, B1:B10 > 50)"),
    fn("Lookup", "SORT", "SORT(array, [sort_index], [order], [by_col])", "Sorted copy of a range. Spills.", "=SORT(A2:C20, 2, -1)"),
    fn("Lookup", "SORTBY", "SORTBY(array, by_array1, [order1], …)", "Sorts by other ranges. Spills.", "=SORTBY(A2:A20, B2:B20, -1)"),
    fn("Lookup", "UNIQUE", "UNIQUE(array, [by_col], [exactly_once])", "Distinct rows. Spills.", "=SORT(UNIQUE(A2:A100))"),
    fn("Lookup", "SEQUENCE", "SEQUENCE(rows, [columns], [start], [step])", "Grid of sequential numbers. Spills.", "=SEQUENCE(5, 2)"),
    fn("Lookup", "TAKE", "TAKE(array, rows, [columns])", "First (or last, if negative) rows/columns.", "=TAKE(A2:C100, 5)"),
    fn("Lookup", "DROP", "DROP(array, rows, [columns])", "Everything except the first/last rows/columns.", "=DROP(A1:C100, 1)"),
    fn("Lookup", "TRANSPOSE", "TRANSPOSE(array)", "Swaps rows and columns.", "=TRANSPOSE(A1:E1)"),
    fn("Lookup", "CHOOSECOLS", "CHOOSECOLS(array, col1, …)", "Picks columns by number (negative counts from the end).", "=CHOOSECOLS(A1:E20, 1, 3)"),
    fn("Lookup", "CHOOSEROWS", "CHOOSEROWS(array, row1, …)", "Picks rows by number.", "=CHOOSEROWS(A1:E20, 1, -1)"),
    fn("Lookup", "VSTACK", "VSTACK(array1, …)", "Stacks ranges vertically.", "=VSTACK(A2:B5, D2:E5)"),
    fn("Lookup", "HSTACK", "HSTACK(array1, …)", "Stacks ranges side by side.", "=HSTACK(A2:A5, C2:C5)"),

    // Text
    fn("Text", "LEFT", "LEFT(text, [num_chars])", "Characters from the start.", "=LEFT(A2, 3)"),
    fn("Text", "RIGHT", "RIGHT(text, [num_chars])", "Characters from the end.", "=RIGHT(A2, 4)"),
    fn("Text", "MID", "MID(text, start, num_chars)", "Characters from the middle.", "=MID(A2, 2, 3)"),
    fn("Text", "LEN", "LEN(text)", "Number of characters.", "=LEN(A2)"),
    fn("Text", "TRIM", "TRIM(text)", "Removes extra spaces.", "=TRIM(A2)"),
    fn("Text", "CLEAN", "CLEAN(text)", "Removes non-printable characters.", "=CLEAN(A2)"),
    fn("Text", "UPPER", "UPPER(text)", "Upper case.", "=UPPER(A2)"),
    fn("Text", "LOWER", "LOWER(text)", "Lower case.", "=LOWER(A2)"),
    fn("Text", "PROPER", "PROPER(text)", "Capitalizes each word.", "=PROPER(A2)"),
    fn("Text", "CONCAT", "CONCAT(text1, …)", "Joins text and ranges.", "=CONCAT(A2:C2)"),
    fn("Text", "CONCATENATE", "CONCATENATE(text1, …)", "Joins text values.", '=CONCATENATE(A2, " ", B2)'),
    fn("Text", "TEXTJOIN", "TEXTJOIN(delimiter, ignore_empty, text1, …)", "Joins with a delimiter.", '=TEXTJOIN(", ", TRUE, A2:A10)'),
    fn("Text", "FIND", "FIND(find_text, within_text, [start])", "Position of text (case-sensitive).", '=FIND("@", A2)'),
    fn("Text", "SEARCH", "SEARCH(find_text, within_text, [start])", "Position of text (any case, wildcards).", '=SEARCH("del*", A2)'),
    fn("Text", "SUBSTITUTE", "SUBSTITUTE(text, old, new, [instance])", "Replaces matching text.", '=SUBSTITUTE(A2, "-", "/")'),
    fn("Text", "REPLACE", "REPLACE(text, start, num_chars, new_text)", "Replaces characters by position.", '=REPLACE(A2, 1, 3, "XYZ")'),
    fn("Text", "EXACT", "EXACT(text1, text2)", "Case-sensitive comparison.", "=EXACT(A2, B2)"),
    fn("Text", "REPT", "REPT(text, times)", "Repeats text.", '=REPT("★", B2)'),
    fn("Text", "CHAR", "CHAR(number)", "Character for a code.", "=CHAR(65)"),
    fn("Text", "CODE", "CODE(text)", "Code of the first character.", '=CODE("A")'),
    fn("Text", "TEXT", "TEXT(value, format)", "Formats a number/date as text.", '=TEXT(B2, "₹#,##0.00")'),
    fn("Text", "VALUE", "VALUE(text)", "Converts text to a number.", '=VALUE("1,234.5")'),
    fn("Text", "TEXTBEFORE", "TEXTBEFORE(text, delimiter, [instance], …)", "Text before a delimiter.", '=TEXTBEFORE(A2, "@")'),
    fn("Text", "TEXTAFTER", "TEXTAFTER(text, delimiter, [instance], …)", "Text after a delimiter.", '=TEXTAFTER(A2, "@")'),
    fn("Text", "TEXTSPLIT", "TEXTSPLIT(text, col_delimiter, [row_delimiter], …)", "Splits text into cells. Spills.", '=TEXTSPLIT(A2, ",")'),

    // Date & time
    fn("Date & Time", "TODAY", "TODAY()", "Today's date.", "=TODAY()"),
    fn("Date & Time", "NOW", "NOW()", "Current date and time.", "=NOW()"),
    fn("Date & Time", "DATE", "DATE(year, month, day)", "Builds a date.", "=DATE(2026, 9, 26)"),
    fn("Date & Time", "TIME", "TIME(hour, minute, second)", "Builds a time.", "=TIME(9, 30, 0)"),
    fn("Date & Time", "DAY", "DAY(date)", "Day of the month.", "=DAY(A2)"),
    fn("Date & Time", "MONTH", "MONTH(date)", "Month number.", "=MONTH(A2)"),
    fn("Date & Time", "YEAR", "YEAR(date)", "Year.", "=YEAR(A2)"),
    fn("Date & Time", "HOUR", "HOUR(time)", "Hour 0–23.", "=HOUR(A2)"),
    fn("Date & Time", "MINUTE", "MINUTE(time)", "Minute 0–59.", "=MINUTE(A2)"),
    fn("Date & Time", "SECOND", "SECOND(time)", "Second 0–59.", "=SECOND(A2)"),
    fn("Date & Time", "WEEKDAY", "WEEKDAY(date, [type])", "Day of week (1 = Sunday by default).", "=WEEKDAY(A2, 2)"),
    fn("Date & Time", "WEEKNUM", "WEEKNUM(date, [type])", "Week of the year (21 = ISO).", "=WEEKNUM(A2)"),
    fn("Date & Time", "EDATE", "EDATE(start_date, months)", "Same day, months later/earlier.", "=EDATE(A2, 3)"),
    fn("Date & Time", "EOMONTH", "EOMONTH(start_date, months)", "Last day of a month.", "=EOMONTH(A2, 0)"),
    fn("Date & Time", "DAYS", "DAYS(end_date, start_date)", "Days between two dates.", "=DAYS(B2, A2)"),
    fn("Date & Time", "DATEDIF", "DATEDIF(start, end, unit)", 'Difference in "Y", "M", "D", "YM", "MD" or "YD".', '=DATEDIF(A2, TODAY(), "Y")'),
    fn("Date & Time", "NETWORKDAYS", "NETWORKDAYS(start, end, [holidays])", "Working days between dates (Mon–Fri).", "=NETWORKDAYS(A2, B2)"),
    fn("Date & Time", "NETWORKDAYS.INTL", "NETWORKDAYS.INTL(start, end, [weekend], [holidays])", 'Working days with a custom weekend (11 = Sunday only, "0000011" …).', "=NETWORKDAYS.INTL(A2, B2, 11)"),
    fn("Date & Time", "WORKDAY", "WORKDAY(start, days, [holidays])", "Date after N working days.", "=WORKDAY(A2, 10)"),
    fn("Date & Time", "WORKDAY.INTL", "WORKDAY.INTL(start, days, [weekend], [holidays])", "WORKDAY with a custom weekend.", "=WORKDAY.INTL(A2, 10, 11)"),
    fn("Date & Time", "DATEVALUE", "DATEVALUE(text)", "Converts date text to a date.", '=DATEVALUE("2026-09-26")'),

    // Financial
    fn("Financial", "PMT", "PMT(rate, nper, pv, [fv], [type])", "Loan payment per period.", "=PMT(0.1/12, 60, -500000)"),
    fn("Financial", "PV", "PV(rate, nper, pmt, [fv], [type])", "Present value.", "=PV(0.08/12, 240, 500)"),
    fn("Financial", "FV", "FV(rate, nper, pmt, [pv], [type])", "Future value.", "=FV(0.06/12, 120, -5000)"),
    fn("Financial", "NPV", "NPV(rate, value1, …)", "Net present value of periodic cash flows.", "=NPV(0.1, B2:B6)"),
    fn("Financial", "IRR", "IRR(values, [guess])", "Internal rate of return.", "=IRR(B2:B7)"),
    fn("Financial", "XNPV", "XNPV(rate, values, dates)", "NPV of dated cash flows.", "=XNPV(0.09, B2:B6, A2:A6)"),
    fn("Financial", "XIRR", "XIRR(values, dates, [guess])", "IRR of dated cash flows.", "=XIRR(B2:B6, A2:A6)"),
    fn("Financial", "RATE", "RATE(nper, pmt, pv, [fv], [type], [guess])", "Interest rate per period.", "=RATE(48, -200, 8000)"),
    fn("Financial", "NPER", "NPER(rate, pmt, pv, [fv], [type])", "Number of periods.", "=NPER(0.01, -100, 1000)"),
    fn("Financial", "IPMT", "IPMT(rate, per, nper, pv, [fv], [type])", "Interest part of a payment.", "=IPMT(0.1/12, 1, 36, 8000)"),
    fn("Financial", "PPMT", "PPMT(rate, per, nper, pv, [fv], [type])", "Principal part of a payment.", "=PPMT(0.1/12, 1, 24, 2000)"),
    fn("Financial", "CUMIPMT", "CUMIPMT(rate, nper, pv, start, end, type)", "Total interest between two periods.", "=CUMIPMT(0.09/12, 360, 125000, 13, 24, 0)"),
    fn("Financial", "CUMPRINC", "CUMPRINC(rate, nper, pv, start, end, type)", "Total principal between two periods.", "=CUMPRINC(0.09/12, 360, 125000, 13, 24, 0)"),

    // Aggregation
    fn("Aggregation", "SUBTOTAL", "SUBTOTAL(function_num, ref1, …)", "1 AVERAGE, 2 COUNT, 3 COUNTA, 4 MAX, 5 MIN, 9 SUM … (skips other SUBTOTALs).", "=SUBTOTAL(9, B2:B50)"),
    fn("Aggregation", "AGGREGATE", "AGGREGATE(function_num, options, ref1, …)", "Like SUBTOTAL with 19 functions; option 6 ignores errors.", "=AGGREGATE(9, 6, B2:B50)"),
];

export const FORMULA_BASICS = [
    { title: "Operators", items: ["+  −  *  /  ^ (power)  % (percent)", "& joins text: =A2&\" \"&B2", "Compare: =  <>  >  <  >=  <="] },
    { title: "References", items: ["A1 relative, $A$1 absolute, A$1 / $A1 mixed (F4 cycles)", "A1:B10 range, A:A whole column, 1:1 whole row", "A1# the whole spilled result of the formula in A1"] },
    { title: "Wildcards (COUNTIF, SUMIFS, MATCH, XLOOKUP, SEARCH)", items: ["* any run of characters", "? exactly one character", "~* ~? a literal * or ?"] },
    { title: "Dynamic arrays", items: ["FILTER, SORT, UNIQUE, SEQUENCE, … fill the cells below/right", "#SPILL! means something is in the way — clear those cells"] },
    { title: "Errors", items: ["#DIV/0! divide by zero · #N/A not found · #VALUE! wrong type", "#REF! bad reference · #NAME? unknown function · #NUM! invalid number", "#SPILL! blocked · #CALC! empty result · #CYCLE! circular reference"] },
];

const sc = (category, keys, action) => ({ category, keys, action });

// `keys` alternatives are separated by " / ". Entries note where a browser
// reserves Excel's key and an alternative is offered instead.
export const SHORTCUT_CATALOG = [
    sc("File & Workbook", "Ctrl+S", "Save"),
    sc("File & Workbook", "Ctrl+O", "Open / import an Excel file"),
    sc("File & Workbook", "Ctrl+Shift+S", "Export (Save As .xlsx)"),
    sc("File & Workbook", "Ctrl+P", "Print the active sheet"),
    sc("File & Workbook", "Ctrl+Z / Ctrl+Y", "Undo / Redo"),
    sc("File & Workbook", "F1", "Open this cheat sheet"),
    sc("File & Workbook", "Ctrl+F1", "Collapse / expand the ribbon"),
    sc("File & Workbook", "Shift+F11 / Alt+Shift+F1", "Insert a new sheet (Ctrl+N is reserved by the browser)"),
    sc("File & Workbook", "Ctrl+Alt+PgUp / Ctrl+Alt+PgDn", "Previous / next sheet (Ctrl+PgUp/PgDn switch browser tabs, so the Ctrl+Alt pair is used)"),

    sc("Editing", "Ctrl+C / Ctrl+X / Ctrl+V", "Copy / Cut / Paste"),
    sc("Editing", "Ctrl+Alt+V", "Paste Special (values, formats, transpose, operations)"),
    sc("Editing", "Delete / Backspace", "Clear contents (formatting stays)"),
    sc("Editing", "F2", "Edit the active cell"),
    sc("Editing", "Esc", "Cancel editing / collapse the selection"),
    sc("Editing", "Enter / Shift+Enter", "Commit and move down / up"),
    sc("Editing", "Tab / Shift+Tab", "Commit and move right / left"),
    sc("Editing", "Ctrl+Enter", "Fill every selected cell with the entry"),
    sc("Editing", "Alt+Enter", "New line inside the cell"),
    sc("Editing", "Ctrl+D / Ctrl+R", "Fill down / fill right"),
    sc("Editing", "F4", "Cycle $ anchoring on the reference at the cursor"),
    sc("Editing", "Alt+=", "AutoSum"),
    sc("Editing", "Ctrl+; / Ctrl+Shift+;", "Insert today's date / the current time"),

    sc("Navigation & Selection", "Arrows", "Move one cell"),
    sc("Navigation & Selection", "Ctrl+Arrows", "Jump to the edge of the data region"),
    sc("Navigation & Selection", "Shift+Arrows / Ctrl+Shift+Arrows", "Extend the selection (to the data edge)"),
    sc("Navigation & Selection", "Home / Ctrl+Home / Ctrl+End", "Column A / cell A1 / last used cell"),
    sc("Navigation & Selection", "PgUp / PgDn", "Up / down one screen"),
    sc("Navigation & Selection", "Alt+PgUp / Alt+PgDn", "Left / right one screen"),
    sc("Navigation & Selection", "Ctrl+A", "Select the current region, press again for the whole sheet"),
    sc("Navigation & Selection", "Ctrl+Space / Shift+Space", "Select the whole column / row"),
    sc("Navigation & Selection", "Ctrl+Shift+Space", "Select the whole sheet"),
    sc("Navigation & Selection", "Ctrl+G / F5", "Go To a cell or range"),
    sc("Navigation & Selection", "Ctrl+F / Ctrl+H", "Find / Replace"),

    sc("Formatting", "Ctrl+B / Ctrl+I / Ctrl+U", "Bold / Italic / Underline"),
    sc("Formatting", "Ctrl+5 / Alt+Shift+5", "Strikethrough (Ctrl+5 is a browser tab key; use Alt+Shift+5)"),
    sc("Formatting", "Ctrl+1 / Ctrl+Shift+F", "Format Cells dialog (Ctrl+1 is a browser tab key; use Ctrl+Shift+F)"),
    sc("Formatting", "Ctrl+Shift+~", "General format"),
    sc("Formatting", "Ctrl+Shift+$", "Currency format"),
    sc("Formatting", "Ctrl+Shift+%", "Percentage format"),
    sc("Formatting", "Ctrl+Shift+^", "Scientific format"),
    sc("Formatting", "Ctrl+Shift+#", "Date format"),
    sc("Formatting", "Ctrl+Shift+@", "Time format"),
    sc("Formatting", "Ctrl+Shift+!", "Number with thousands separator, 2 decimals"),
    sc("Formatting", "Alt+H, W", "Toggle Wrap Text"),
    sc("Formatting", "Alt+H, M, C", "Merge & Center"),

    sc("Rows, Columns & Sheets", "Ctrl++ / Ctrl+Shift+=", "Insert rows/columns"),
    sc("Rows, Columns & Sheets", "Ctrl+-", "Delete rows/columns"),
    sc("Rows, Columns & Sheets", "Ctrl+9 / Ctrl+Alt+9", "Hide rows (Ctrl+9 is a browser tab key; use Ctrl+Alt+9)"),
    sc("Rows, Columns & Sheets", "Ctrl+Shift+9", "Unhide rows in the selection"),
    sc("Rows, Columns & Sheets", "Ctrl+0", "Hide columns"),
    sc("Rows, Columns & Sheets", "Ctrl+Shift+0", "Unhide columns in the selection"),
    sc("Rows, Columns & Sheets", "Alt+H, O, I", "AutoFit column width"),
    sc("Rows, Columns & Sheets", "Alt+H, O, A", "AutoFit row height"),
    sc("Rows, Columns & Sheets", "Alt+O, H, R", "Rename the sheet"),
    sc("Rows, Columns & Sheets", "Alt+O, H, H / Alt+O, H, U", "Hide / unhide sheets"),

    sc("Calculation & Data", "F9 / Shift+F9", "Recalculate (re-rolls RAND, refreshes NOW/TODAY)"),
    sc("Calculation & Data", "Ctrl+L / Ctrl+T", "Format as Table (Ctrl+T is reserved by the browser; use Ctrl+L)"),
    sc("Calculation & Data", "Ctrl+Shift+L", "Toggle AutoFilter"),
    sc("Calculation & Data", "Ctrl+`", "Show formulas instead of results"),
];
